// Generated by ts-to-zod
import { z } from "zod";

export const AccountSchema = z.object({
  token: z.string(),
  username: z.string(),
  firstName: z.string(),
  lastName: z.string(),
  role: z.string().nullable(),
}).passthrough();

export const PerformanceStatsSchema = z.object({
  totalturns: z.number(),
  remaininghealth: z.number(),
  maxhealth: z.number(),
  healthpercentage: z.number(),
  correctanswers: z.number(),
  wronganswers: z.number(),
  accuracy: z.number(),
  totaldamage_dealt: z.number(),  // ✅ MATCH SA C#
  totaldamage_taken: z.number(),  // ✅ MATCH SA C#
}).passthrough();

export const LevelCompletionSchema = z.object({
  id: z.string(),
  duration: z.number().default(0),
  starsEarned: z.number(),
  completedAt: z.string(),
  performance: PerformanceStatsSchema.optional(),
}).passthrough();

export const ProgressionSchema = z.object({
  totalStarsEarned: z.number(),
  levelsFinished: z.array(LevelCompletionSchema),
  current_level_id: z.string().optional(),
}).passthrough();

export const InventoryItemSchema = z.object({
  id: z.string(),
  quantity: z.number(),
  acquiredAt: z.string(),
}).passthrough();

export const PurchaseHistoryItemSchema = z.object({
  id: z.string(),
  quantity: z.number(),
  cost: z.number(),
  purchasedAt: z.string(),
}).passthrough();

export const ShopSchema = z.object({
  stars: z.number(),
  purchaseHistory: z.array(PurchaseHistoryItemSchema),
}).passthrough();

export const SaveSchema = z.object({
  account: AccountSchema.optional(),
  progression: ProgressionSchema,
  inventory: z.array(InventoryItemSchema),
  shop: ShopSchema,
}).passthrough();
