// Generated by ts-to-zod
import { z } from "zod";

export const AccountSchema = z.object({
  token: z.string(),
  username: z.string(),
  firstName: z.string(),
  lastName: z.string(),
  role: z.string(),
});

export const LevelCompletionSchema = z.object({
  id: z.string(),
  duration: z.number(),
  starsEarned: z.number(),
  completedAt: z.string(),
});

export const progressionSchema = z.object({
  totalStarsEarned: z.number(),
  levelsFinished: z.array(LevelCompletionSchema),
});

export const InventoryItemSchema = z.object({
  id: z.string(),
  quantity: z.number(),
  acquiredAt: z.string(),
});

export const PurchaseHistoryItemSchema = z.object({
  id: z.string(),
  quantity: z.number(),
  cost: z.number(),
  purchasedAt: z.string(),
});

export const shopSchema = z.object({
  stars: z.number(),
  purchaseHistory: z.array(PurchaseHistoryItemSchema),
});

export const SaveSchema = z.object({
  account: AccountSchema.nullish(),
  progression: progressionSchema,
  inventory: z.array(InventoryItemSchema),
  shop: shopSchema,
});
